### ISSUE TITLE
Loading map.bikewise.org does not display map layer

### ISSUE THREAD

**Issue by stevepiercy** [bikeindex/bike_thefts_map#4]
It looks like y'all need to update your plan at mapbox.

https://map.bikewise.org/#5/40.814/-94.702

In the Network tab of Chrome, I found a bunch of 410 Gone errors.

`{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}`

It looks like it will still be free for up to 50K requests.

https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4

https://www.mapbox.com/pricing/#session-user-pricing

**Comment by sethherr** [comment]
Thanks! Looking into it now

**Comment by sethherr** [comment]
#6 did fix it!

Had to mess around with a number of things to get it working, thanks for getting it started and pointing me in the right direction @stevepiercy !
